/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Daren
 */
public class Login extends java.awt.Frame {

    /**
     * Creates new form NewFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        nuevouser = new javax.swing.JButton();
        correo = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        iniciarSesionbtn1 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        mensajes = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        nuevouser.setText("Nuevo Usuario");
        jLayeredPane1.add(nuevouser);
        nuevouser.setBounds(220, 300, 160, 23);

        correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correo.setText("Correo");
        jLayeredPane1.add(correo);
        correo.setBounds(150, 110, 300, 30);

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("contraseña");
        jLayeredPane1.add(password);
        password.setBounds(150, 170, 300, 30);

        iniciarSesionbtn1.setText("Iniciar Sesion");
        jLayeredPane1.add(iniciarSesionbtn1);
        iniciarSesionbtn1.setBounds(220, 250, 160, 23);

        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(error);
        error.setBounds(80, 350, 490, 0);

        mensajes.setForeground(new java.awt.Color(255, 51, 51));
        mensajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.add(mensajes);
        mensajes.setBounds(44, 350, 520, 0);

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 616, 439);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField correo;
    public javax.swing.JLabel error;
    public javax.swing.JButton iniciarSesionbtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel mensajes;
    public javax.swing.JButton nuevouser;
    public javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
